### ISSUE TITLE
Lopang setup

### ISSUE THREAD

**Issue by 5475616e** [any-other-guy/Endless-Chaos-LostArk#15]
Hey, what’s the extra setup for lopang? Thanks

**Comment by any-other-guy** [comment]
Set your first bifrost point to be at lopang island.
[Exact location](../blob/main/screenshots/lopangNPC.png) to be right in front of the NPC machine which stands farthest to the entrance. 
Then set your 2/4/5 (because i dont have no3 unlocked) bifrost location to be right in front of those three lopang quest hand-in NPCs.
