### ISSUE TITLE
Issues with running the bot since the 22/05/24 update (not moving at floor1 then alt+f4) SOLVED

### ISSUE THREAD

**Issue by mololo9** [any-other-guy/Endless-Chaos-LostArk#77]
When the character enters the chaos it doesnt move and the last message on the CMD is "loadind" before it alt+f4 and tries to restart the game

on the CMD the following is displayed :
Endless Chaos starting in seconds...
Remember to turn on Auto-disassemble
city loaded
floor1
loading
alt f4

meaning that it enters the ELIF from line 297 (can be like 3/4 lines before since i added options to do 1580 1600 1610 chaos), but then it tries to do the waitForLoading() function from line 2325 but it (i suppose)
alt+f4 because of the timelimit set by BlackScreenTimeLimit, but then even when i increase that limit my character just won't move, so i suppose i'm stuck in the waitForLoading() function, didnt do anything in any of the files and the bot was working just fine and i was using it since 23/07/23
![Screen1](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/170808563/e6259aa4-9029-4739-b420-a6f8b5cb922a)
![Screen2](https://github.com/any-other-guy/LostArk-Endless-Chaos/assets/170808563/53a4eb25-06de-44df-bf3e-54c8b24881fa)

i've already updated all of the modules in the requirements.txt file with both those commands :

pip install -r requirements.txt --upgrade
py -m pip install -r requirements.txt --upgrade

i tried to not use the waitForLoading() and it works (also had to change the healthCheck() function from line 2477) but wouldnt quit at the end of floor3 when the dungeon is cleared

i just want to understand why it stopped working from 21/05/24 to 22/05/24 when i didn't change a thing
everything is set correctly and hasnt moved since almost a year now:

- Resolution: 1920x1080
- Screen: Borderless
- Force 21:9 Aspect Ratio checked

In-game Gameplay -> Controls and Display -> HUD size: 110%
minimap transparency (at top right corner): 100%
minimap zoom-in (at top right corner): 65%

i'd appreciate anyone helping or just telling if you've ran or are running into this problem.

thank you

**Comment by muraza** [comment]
lol I'm glad you made this post since I stopped playing for a while and just got back to the game after a month. I upgraded to windows 11 to fix lag and it fucked up my python environment which I spent a bunch of time fixing so I would've probably went down the wrong rabbit hole thinking this error was also related.

Anyways I digress, **they changed what the leave button looks like so the bot never leaves the waitForLoading() function**. You just need to take a new screenshot of the exit button and replace the leave.png file in the screenshots folder with the new one. 

By the way, you were almost at the solution yourself, that was a good investigation. Especially with tools like chatGPT nowadays you could definitely have found the root cause yourself. Next time I would recommend plugging in the waitForLoading function into chatGPT and asking it when the function exits (Since you were already aware it's stuck in the waitForLoading function). From there it would've been easy to understand that it is related to the leave button. But I hope you would still come and share your findings so people like me can also benefit! :)

**Comment by mololo9** [comment]
First of all let me express my sincere gratitude, taking another screenshot and swapping pictures solved my issue.

Not only that, you also made me realize i could have solved it with those clues but also from past experience, i ran into something similar when the game swapped back to my native language and i had to switch it back to english for pictures to match, i'm glad me being impatient could benefit you.

I thought it was because of modules (pyautogui, pydirectinput, ...) because i'm not familiar with those so i went and tried to uninstall reinstall everything from python to those modules without even checking if the game had changed some icons. Going through the bot.py file with some print() here and there helped me understanding it better and i did some cleaning deleting functions i'll never use and comments that were left there, i'll try to "rewrite" bot.py to my liking so that i can navigate and have an easier time targetting issues when they come, also i'll definitely check coding with AI that sure sounds interesting.

Thanks again

Have a good one :)
